import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || '/Users/shantanu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const origin=process.env.TEST_ORIGIN||'http://localhost:5173';
const browser=await chromium.launch({headless:true,executablePath:process.env.TEST_BROWSER_PATH});
const context=await browser.newContext({viewport:{width:1365,height:1000}});
const page=await context.newPage();const issues=[];page.on('pageerror',e=>issues.push(e.message));
async function api(path,body,ctx=context){const r=body===undefined?await ctx.request.get(origin+path):await ctx.request.post(origin+path,{data:body});return {status:r.status(),data:await r.json()};}
let tests=0;function ok(name){tests++;console.log(`PASS ${name}`);}
try{
 await page.goto(origin+'/signin-with-chatgpt?return_to=/');
 await page.getByRole('heading',{name:'Your next conversation starts here.'}).waitFor();
 await page.getByText('Opening your workspace…').waitFor({state:'hidden'});
 await page.getByRole('button',{name:/Priya Sharma/}).first().waitFor();
 await page.screenshot({path:'outputs/desktop.png',fullPage:true});ok('authenticated dashboard loads persisted sample data');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await page.screenshot({path:'outputs/mobile.png',fullPage:true});ok('mobile dashboard has no horizontal overflow');
 await page.getByRole('button',{name:/Priya Sharma/}).first().click();
 await page.getByRole('heading',{name:'Other registrations'}).waitFor();
 await page.getByText('Exams overlap with this batch.',{exact:false}).waitFor();
 await page.screenshot({path:'outputs/contact-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Close',exact:true}).click();ok('returning contact history is visible');
 const before=await api('/api/desk');assert.equal(before.status,200);
 const unauth=await browser.newContext();const denied=await api('/api/desk',undefined,unauth);assert.equal(denied.status,401);ok('anonymous admin data access denied');
 const future=new Date(Date.now()+14*86400000).toISOString().slice(0,10)+'T18:00';
 const title='QA webinar '+Date.now();
 await page.getByRole('tab',{name:'Webinars',exact:true}).click();
 await page.locator('.webinar-card').first().getByRole('button',{name:'Duplicate',exact:true}).click();
 await page.getByLabel('Webinar title',{exact:true}).fill(title);
 await page.getByLabel('Target batch',{exact:true}).fill('QA next batch');
 await page.getByLabel('Webinar date and time · IST',{exact:true}).fill(future);
 await page.getByLabel('Webinar joining link',{exact:true}).fill('https://example.com/demo-webinar');
 await page.getByRole('combobox',{name:'Registration status'}).click();
 await page.getByRole('option',{name:'Open registration'}).click();
 await page.getByRole('button',{name:'Save webinar',exact:true}).click();
 await page.getByRole('heading',{name:title,exact:true}).waitFor();
 const state=(await api('/api/desk')).data;
 const w=state.webinars.find(w=>w.title===title);assert.ok(w);assert.equal(state.leads.filter(l=>l.webinar_id===w.id).length,0);ok('duplicate copies configuration without old registrations');
 const publicInfo=await api('/api/register/'+w.id,undefined,unauth);assert.equal(publicInfo.status,200);assert.equal(publicInfo.data.webinar.owner,undefined);assert.equal(publicInfo.data.webinar.join_url,undefined);ok('public endpoint exposes webinar details without private data');
 const formPage=await unauth.newPage();await formPage.setViewportSize({width:390,height:844});
 await formPage.goto(origin+'/register/'+w.id);
 await formPage.getByRole('heading',{name:"Let's get to know you."}).waitFor();
 await formPage.getByLabel('Your name',{exact:true}).fill('QA Returning Learner');
 const phone='+1555'+String(Date.now()).slice(-7);
 await formPage.getByRole('textbox',{name:/WhatsApp number/}).fill(phone);
 await formPage.getByRole('combobox',{name:'Current situation'}).click();
 await formPage.getByRole('option',{name:'Graduate looking for work'}).click();
 await formPage.getByRole('checkbox',{name:'Webinar WhatsApp permission'}).check();
 await formPage.getByRole('checkbox',{name:'Course follow-up permission'}).check();
 assert.equal(await formPage.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await formPage.screenshot({path:'outputs/registration-mobile.png',fullPage:true});
 await formPage.getByRole('button',{name:'Register for the webinar'}).click();
 await formPage.getByRole('heading',{name:'Your registration is received.'}).waitFor();ok('public mobile form saves a graduate registration');
 const form={name:'QA Returning Learner',phone,situation:'Graduate looking for work',college:'',study:'',goal:'A job-ready portfolio',webinar_consent:true,followup_consent:true,website:''};
 const dup=await api('/api/register/'+w.id,form,unauth);assert.equal(dup.status,200);
 let all=(await api('/api/desk')).data;let lead=all.leads.find(l=>l.phone===phone);assert.ok(lead);assert.equal(all.leads.filter(l=>l.phone===phone).length,1);ok('duplicate registration does not create duplicate contacts');
 const update={action:'update_lead',lead:{id:lead.id,version:lead.version,status:'Interested',next_at:null,attendance:'Unknown',note:'Asked for a callback.',outcome:'Requested callback',do_not_contact:false}};
 assert.equal((await api('/api/desk',update)).status,400);ok('interested leads require a next follow-up');
 update.lead.next_at=new Date(Date.now()+86400000).toISOString();let saved=await api('/api/desk',update);assert.equal(saved.status,200);assert.equal(saved.data.state.leads.find(l=>l.id===lead.id).status,'Interested');assert.equal((await api('/api/desk',update)).status,409);ok('follow-ups persist and stale edits are rejected');
 lead=saved.data.state.leads.find(l=>l.id===lead.id);
 const send={action:'simulate_invitations',webinar_id:w.id,registration_ids:[lead.id]};
 const [one,two]=await Promise.all([api('/api/desk',send),api('/api/desk',send)]);assert.equal(one.status,200);assert.equal(two.status,200);assert.equal(one.data.result+two.data.result,1);all=(await api('/api/desk')).data;assert.equal(all.messages.filter(m=>m.registration_id===lead.id).length,1);assert.equal(all.messages.find(m=>m.registration_id===lead.id).state,'Simulated');ok('concurrent invitation triggers create only one clearly simulated message');
 const original=all.webinars.find(x=>x.sample&&x.status==='open');await api('/api/register/'+original.id,form,unauth);all=(await api('/api/desk')).data;const history=all.leads.filter(l=>l.phone===phone);assert.equal(history.length,2);assert.equal(history[0].contact_id,history[1].contact_id);ok('new webinar registration links to the existing contact history');
 const newLead=history.find(l=>l.webinar_id===original.id);let block=await api('/api/desk',{action:'update_lead',lead:{id:lead.id,version:lead.version,status:'Not interested in this batch',next_at:null,attendance:'Unknown',note:'Do not contact test.',outcome:'Status update',do_not_contact:true}});assert.equal(block.status,200);assert.ok(block.data.state.leads.filter(l=>l.phone===phone).every(l=>l.do_not_contact===1));assert.equal((await api('/api/desk',{action:'simulate_invitations',webinar_id:original.id,registration_ids:[newLead.id]})).status,400);ok('do-not-contact applies across batches and excludes invitations');
 const closed=all.webinars.find(x=>x.status==='closed');assert.equal((await api('/api/register/'+closed.id,{...form,phone:'+15559999998'},unauth)).status,410);ok('closed webinars reject registration');
 const invalid=await api('/api/desk',{action:'save_webinar',id:original.id,webinar:{...original,join_url:'javascript:alert(1)'}});assert.equal(invalid.status,400);ok('unsafe webinar URLs rejected');
 await page.reload();await page.getByText('Opening your workspace…').waitFor({state:'hidden'});await page.getByRole('tab',{name:'People',exact:true}).click();await page.getByRole('textbox',{name:'Search people'}).fill(phone);await page.getByRole('heading',{name:'QA Returning Learner'}).first().waitFor();ok('saved contacts survive page reload');
 assert.deepEqual(issues,[]);ok('no browser runtime errors');
 console.log(JSON.stringify({passed:tests,webmcp:'Unavailable in the browser runtime; feature-detected registration reviewed.',screenshots:['desktop.png','mobile.png','contact-mobile.png','registration-mobile.png']}));
}catch(e){await page.screenshot({path:'outputs/test-failure.png',fullPage:true});console.log((await page.locator('body').innerText()).slice(-7000));throw e;}finally{await browser.close();}
